name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: "Install dependencies"
        working-directory: ts
        run: npm i
      - name: "ESLint the ESLint config"
        working-directory: ts
        run: npx eslint -c basic.eslint.config.js basic.eslint.config.js eslint.config.js
      - name: "ESLint"
        working-directory: ts
        run: npx eslint src
      - name: "Compile TypeScript"
        working-directory: ts
        run: npm run build
